export { ClinicsList } from "./components/clinics-list"
export { ClinicDetailView } from "./components/clinic-detail"
export { ClinicDialog } from "./components/clinic-dialog"
export { ClinicForm } from "./components/clinic-form"
export { useClinics, useClinic, useCreateClinic, useUpdateClinic, useDeactivateClinic, useDeleteClinic, useClinicSubscription } from "./hooks"
export { getClinicsApi, getClinicApi, createClinicApi, updateClinicApi, deleteClinicApi, getPlansApi } from "./services/clinics.service"
export { getClinicSubscriptionApi } from "./services/subscription.service"
export type { Clinic, ClinicStatus, SubscriptionInfo, PlanOption } from "./types"
